---
# roles/mdns/handlers/
- name: Restart and enable systemd-resolved
  become: true
  when: ansible_os_family == 'Debian'
  ansible.builtin.systemd_service:
    name: systemd-resolved
    daemon_reload: true
    enabled: true
    state: restarted

- name: Restart and enable avahi daemon
  become: true
  when: ansible_os_family == 'RedHat'
  ansible.builtin.systemd_service:
    name: avahi-daemon
    daemon_reload: true
    enabled: true
    state: restarted
