---
argument_specs:
  main:
    short_description: Main entry point for the podman role.
    description:
      - Main entrypoint for podman role.
    author:
      - Chun Pan Yung
    options:
      podman_data_dir:
        type: "str"
        required: false
        default: "/srv/containers"
        description:
          - "Local directory uses for all podman volumes."
          - "It will change the SELinux context to 'container_file_t' recursively."
