---
- name: Execute following tasks with sudo
  become: true
  block:
    - name: Install Auto Update and Auto Upgrade
      ansible.builtin.apt:
        name: unattended-upgrades  # auto install of updates

    - name: Configure unattended-upgrades
      ansible.builtin.copy:
        src: 52unattended-upgrades-local
        dest: /etc/apt/apt.conf.d/
        owner: root
        group: root
        mode: '0755'
